server:
  port: 9001
spring:
  application:
    name: admin  #微服务的名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #配置mybatis-plus的
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/driver?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root